// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cookies.sql

package database

import (
	"context"
)

const createCookie = `-- name: CreateCookie :one
INSERT INTO cookies (
 userid,
 cookie
)
VALUES (?, ? )
RETURNING id
`

type CreateCookieParams struct {
	Userid int64  `json:"userid"`
	Cookie string `json:"cookie"`
}

func (q *Queries) CreateCookie(ctx context.Context, arg CreateCookieParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCookie, arg.Userid, arg.Cookie)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCookie = `-- name: DeleteCookie :exec
DELETE FROM cookies
WHERE id = ?
`

func (q *Queries) DeleteCookie(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCookie, id)
	return err
}

const readAllCookies = `-- name: ReadAllCookies :many
SELECT id, userid, cookie FROM cookies
`

func (q *Queries) ReadAllCookies(ctx context.Context) ([]Cookie, error) {
	rows, err := q.db.QueryContext(ctx, readAllCookies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cookie
	for rows.Next() {
		var i Cookie
		if err := rows.Scan(&i.ID, &i.Userid, &i.Cookie); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readCookie = `-- name: ReadCookie :one
SELECT id, userid, cookie
FROM cookies
WHERE id = ?
`

func (q *Queries) ReadCookie(ctx context.Context, id int64) (Cookie, error) {
	row := q.db.QueryRowContext(ctx, readCookie, id)
	var i Cookie
	err := row.Scan(&i.ID, &i.Userid, &i.Cookie)
	return i, err
}

const updateCookie = `-- name: UpdateCookie :exec
UPDATE cookies
SET userid = ?,
    cookie = ?
WHERE id = ?
`

type UpdateCookieParams struct {
	Userid int64  `json:"userid"`
	Cookie string `json:"cookie"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateCookie(ctx context.Context, arg UpdateCookieParams) error {
	_, err := q.db.ExecContext(ctx, updateCookie, arg.Userid, arg.Cookie, arg.ID)
	return err
}
