// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type User struct {
	ID        int64          `json:"id"`
	Nickname  string         `json:"nickname"`
	Age       sql.NullInt64  `json:"age"`
	Gender    sql.NullString `json:"gender"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
}
