// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Cookie struct {
	ID     int64  `json:"id"`
	Userid int64  `json:"userid"`
	Cookie string `json:"cookie"`
}

type User struct {
	ID        int64  `json:"id"`
	Nickname  string `json:"nickname"`
	Age       int64  `json:"age"`
	Gender    string `json:"gender"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}
